kind: secret
type: docker
name: default

steps:
- name: install
  image: node:16-alpine3.12
  commands:
    - npm install
  when:
    branch:
      include: [ master ]
    event:
      - commit
      - push
      - pull_request


- name: build/client
  image: node:16-alpine3.12
  environment:
    NODE_ENV: production
  secrets: [ ssh_key ]
  commands:
    - npm run generate
  when:
    branch:
      include: [ master ]
    event:
      - push
      - pull_request


- name: deploy
  image: node:16-alpine3.12
  secrets: [ ssh_key ]
  commands:
    - npm install gulp
    - npm run deploy
  when:
    branch:
      include: [ master ]
    event:
      - push
      - pull_request
